security:
  # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    db_provider:
      entity:
        class: App\Entity\User

  firewalls:
      # dev:
      #   pattern: ^/(_(profiler|wdt)|css|images|js)/
      #   security: false
      main:
        anonymous: ~
        pattern: ^/
        provider: db_provider
        form_login:
          login_path: session_login
          check_path: session_login

  encoders:
    App\Entity\User:
      algorithm: bcrypt
