default:
  resource: 'App\Controller\DefaultController'
  type:     annotation

item:
  resource: 'App\Controller\ItemController'
  type:     annotation

cart:
  resource: 'App\Controller\CartController'
  type:     annotation
